### ISSUE TITLE
NPE on tm.getNeighboringCellInfo()

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#383]
```
04-22 21:16:45.773  16114-16114/com.SecUpwN.AIMSICD E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.SecUpwN.AIMSICD, PID: 16114
    java.lang.NullPointerException
            at com.SecUpwN.AIMSICD.service.CellTracker.checkForNeighbourCount(CellTracker.java:540)
            at com.SecUpwN.AIMSICD.service.CellTracker$2.onCellLocationChanged(CellTracker.java:764)
            at android.telephony.PhoneStateListener$2.handleMessage(PhoneStateListener.java:384)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

On line:

```
        Integer ncls = tm.getNeighboringCellInfo().size(); // NC list size
```

I'm unable to start the application after uninstalling(not just reinstalling) and installing fresh version.

**Comment by SecUpwN** [comment]
@agilob,  have just sent you the APK with your latest PR added. Please verify this is fixed and close it.

**Comment by agilob** [comment]
I made another PR fixing this issue.
