### ISSUE TITLE
Application dies when running in background

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#390]
When I turn on location service (from no location service to GPS) application crashes after a few seconds:

```
04-24 20:30:38.720 W/PackageParser(2087): No actions in intent filter at /system/priv-app/com.SecUpwN.AIMSICD-2.apk Binary XML file line #147
04-24 20:30:38.720 W/PackageParser(2087): No actions in intent filter at /system/priv-app/com.SecUpwN.AIMSICD-2.apk Binary XML file line #172
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.INTERACT_ACROSS_USERS_FULL to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.DEVICE_POWER to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.DIAGNOSTIC to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.FACTORY_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.HARDWARE_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.INJECT_EVENTS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission android.permission.INTERNAL_SYSTEM_WINDOW to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission android.phone.receiveDetailedCallState in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Not granting permission com.android.permission.HANDOVER_STATUS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.app.controlpanel.permission.PRIVATE in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.app.factorymode.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.app.cm.permission.PERMISSION_MANAGEMENT in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.app.phoneutil.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.app.servicemodeapp.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.DATA_ROAMING_SETTINGS_ENHANCED in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.READ_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.WRITE_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.factory.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission com.sec.modem.settings.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:50.161 W/PackageManager(2087): Unknown permission org.simalliance.openmobileapi.SMARTCARD in package com.SecUpwN.AIMSICD
04-24 20:30:51.953 W/PackageManager(2087): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.SecUpwN.AIMSICD
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.INTERACT_ACROSS_USERS_FULL to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.DEVICE_POWER to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.DIAGNOSTIC to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.FACTORY_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.HARDWARE_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.INJECT_EVENTS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.953 W/PackageManager(2087): Not granting permission android.permission.INTERNAL_SYSTEM_WINDOW to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission android.phone.receiveDetailedCallState in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Not granting permission com.android.permission.HANDOVER_STATUS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40083e47)
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.app.controlpanel.permission.PRIVATE in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.app.factorymode.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.app.cm.permission.PERMISSION_MANAGEMENT in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.app.phoneutil.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.app.servicemodeapp.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.DATA_ROAMING_SETTINGS_ENHANCED in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.READ_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.WRITE_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.factory.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission com.sec.modem.settings.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:51.963 W/PackageManager(2087): Unknown permission org.simalliance.openmobileapi.SMARTCARD in package com.SecUpwN.AIMSICD
04-24 20:30:57.268 W/PackageManager(2087): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.SecUpwN.AIMSICD
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.INTERACT_ACROSS_USERS_FULL to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.DEVICE_POWER to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.DIAGNOSTIC to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.FACTORY_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.HARDWARE_TEST to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.INJECT_EVENTS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.268 W/PackageManager(2087): Not granting permission android.permission.INTERNAL_SYSTEM_WINDOW to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission android.phone.receiveDetailedCallState in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Not granting permission com.android.permission.HANDOVER_STATUS to package com.SecUpwN.AIMSICD (protectionLevel=2 flags=0x40883e47)
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.app.controlpanel.permission.PRIVATE in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.app.factorymode.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.app.cm.permission.PERMISSION_MANAGEMENT in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.app.phoneutil.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.app.servicemodeapp.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.DATA_ROAMING_SETTINGS_ENHANCED in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.READ_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.android.phone.permission.WRITE_CALL_SETTINGS in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.factory.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission com.sec.modem.settings.permission.KEYSTRING in package com.SecUpwN.AIMSICD
04-24 20:30:57.278 W/PackageManager(2087): Unknown permission org.simalliance.openmobileapi.SMARTCARD in package com.SecUpwN.AIMSICD
04-24 20:31:13.450 I/ActivityManager(2087): Start proc com.SecUpwN.AIMSICD for broadcast com.SecUpwN.AIMSICD/.receiver.BootCompletedReceiver: pid=2900 uid=10158 gids={50158, 3003, 1028, 1023, 1007, 1015, 3006}
04-24 20:31:13.550 D/ActivityThread(2900): handleBindApplication:com.SecUpwN.AIMSICD
04-24 20:31:45.871 I/ActivityManager(2087): Killing 2900:com.SecUpwN.AIMSICD/u0a158 (adj 15): empty #17
04-25 08:08:02.892 I/Timeline(2749): Timeline: Activity_launch_request id:com.SecUpwN.AIMSICD time:41682975
04-25 08:08:02.892 I/ActivityManager(2087): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD} from pid 2749
04-25 08:08:03.132 I/ActivityManager(2087): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=14975 uid=10158 gids={50158, 3003, 1028, 1023, 1007, 1015, 3006}
04-25 08:08:03.252 D/ActivityThread(14975): handleBindApplication:com.SecUpwN.AIMSICD
04-25 08:08:03.863 I/AIMSICD_Service(14975): Service launched successfully.
04-25 08:08:04.383 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:04.413 D/AIMSICD (14975): CellTracker: NC list not supported by AOS on this device. Nothing to do. CID: 6259818
04-25 08:08:04.413 D/AIMSICD (14975): CellTracker: Setting nc_list_present to: false
04-25 08:08:04.603 V/AIMSICD (14975): LAC checked - no change on CID:6259818 LAC(API): 22095 LAC(DBi): 22095
04-25 08:08:04.643 I/AIMSICD_SignalStrengthTracker(14975): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 29744 ms.
04-25 08:08:04.924 I/ActivityManager(2087): Displayed com.SecUpwN.AIMSICD/.AIMSICD: +1s801ms
04-25 08:08:04.924 I/Timeline(2087): Timeline: Activity_windows_visible id: ActivityRecord{41e527c0 u0 com.SecUpwN.AIMSICD/.AIMSICD t4} time:41685002
04-25 08:08:05.004 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:05.094 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:18.187 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:18.277 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:20.669 I/AIMSICD_SignalStrengthTracker(14975): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 13719 ms.
04-25 08:08:24.743 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:25.083 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:25.233 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:25.584 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:25.714 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:25.814 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:37.575 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:37.726 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:38.516 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:38.586 V/AIMSICD (14975): DbAdapter: Cell info updated in local db: 6259818
04-25 08:08:44.672 I/AIMSICD_SignalStrengthTracker(14975): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 23726 ms.
04-25 08:08:44.732 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:45.063 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:45.163 E/AndroidRuntime(14975): Process: com.SecUpwN.AIMSICD, PID: 14975
04-25 08:08:45.163 E/AndroidRuntime(14975): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.locationExists(AIMSICDDbAdapter.java:602)
04-25 08:08:45.163 E/AndroidRuntime(14975): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertLocation(AIMSICDDbAdapter.java:418)
04-25 08:08:45.163 E/AndroidRuntime(14975): 	at com.SecUpwN.AIMSICD.service.CellTracker.onLocationChanged(CellTracker.java:987)
04-25 08:08:45.163 E/AndroidRuntime(14975): 	at com.SecUpwN.AIMSICD.service.AimsicdService$5.onLocationChanged(AimsicdService.java:274)
04-25 08:08:45.163 E/AndroidRuntime(14975): 	at com.SecUpwN.AIMSICD.service.LocationTracker$MyLocationListener.onLocationChanged(LocationTracker.java:152)
04-25 08:08:46.855 I/ActivityManager(2087): Process com.SecUpwN.AIMSICD (pid 14975) has died.
04-25 08:08:46.855 I/WindowState(2087): WIN DEATH: Window{425e1178 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
04-25 08:08:46.855 W/ActivityManager(2087): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
04-25 08:08:46.855 F/ProcessStats(2087): Starting service ServiceState{4252bde8 com.SecUpwN.AIMSICD.service.AimsicdService pkg=com.SecUpwN.AIMSICD proc=4252bde8} without owner
04-25 08:08:47.876 I/ActivityManager(2087): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=15139 uid=10158 gids={50158, 3003, 1028, 1023, 1007, 1015, 3006}
04-25 08:08:47.936 D/ActivityThread(15139): handleBindApplication:com.SecUpwN.AIMSICD
04-25 08:08:48.146 I/AIMSICD_Service(15139): Service launched successfully.
04-25 08:08:48.196 D/AIMSICD (15139): CellTracker: NC list not supported by AOS on this device. Nothing to do. CID: 6259818
04-25 08:08:48.196 D/AIMSICD (15139): CellTracker: Setting nc_list_present to: false
04-25 08:08:48.266 V/AIMSICD (15139): LAC checked - no change on CID:6259818 LAC(API): 22095 LAC(DBi): 22095
04-25 08:08:48.306 I/AIMSICD_SignalStrengthTracker(15139): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 29660 ms.
04-25 08:08:48.436 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:08:48.496 E/AndroidRuntime(15139): Process: com.SecUpwN.AIMSICD, PID: 15139
04-25 08:08:48.496 E/AndroidRuntime(15139): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.locationExists(AIMSICDDbAdapter.java:602)
04-25 08:08:48.496 E/AndroidRuntime(15139): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertLocation(AIMSICDDbAdapter.java:418)
04-25 08:08:48.496 E/AndroidRuntime(15139): 	at com.SecUpwN.AIMSICD.service.CellTracker.onLocationChanged(CellTracker.java:987)
04-25 08:08:48.496 E/AndroidRuntime(15139): 	at com.SecUpwN.AIMSICD.service.AimsicdService$5.onLocationChanged(AimsicdService.java:274)
04-25 08:08:48.496 E/AndroidRuntime(15139): 	at com.SecUpwN.AIMSICD.service.LocationTracker$MyLocationListener.onLocationChanged(LocationTracker.java:152)
04-25 08:08:49.857 I/ActivityManager(2087): Process com.SecUpwN.AIMSICD (pid 15139) has died.
04-25 08:08:49.857 W/ActivityManager(2087): Service crashed 2 times, stopping: ServiceRecord{425230c0 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
04-25 08:08:50.188 W/NotificationService(2087): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@421d0058 in package com.SecUpwN.AIMSICD
04-25 08:08:50.188 W/NotificationService(2087): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@42375080 in package com.SecUpwN.AIMSICD
04-25 08:09:36.554 I/Timeline(2749): Timeline: Activity_launch_request id:com.SecUpwN.AIMSICD time:41776638
04-25 08:09:36.565 I/ActivityManager(2087): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD} from pid 2749
04-25 08:09:36.695 I/ActivityManager(2087): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=15378 uid=10158 gids={50158, 3003, 1028, 1023, 1007, 1015, 3006}
04-25 08:09:36.785 D/ActivityThread(15378): handleBindApplication:com.SecUpwN.AIMSICD
04-25 08:09:37.535 I/AIMSICD_Service(15378): Service launched successfully.
04-25 08:09:37.956 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:09:37.996 D/AIMSICD (15378): CellTracker: NC list not supported by AOS on this device. Nothing to do. CID: 6259818
04-25 08:09:37.996 D/AIMSICD (15378): CellTracker: Setting nc_list_present to: false
04-25 08:09:38.066 V/AIMSICD (15378): LAC checked - no change on CID:6259818 LAC(API): 22095 LAC(DBi): 22095
04-25 08:09:38.086 I/AIMSICD_SignalStrengthTracker(15378): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 29858 ms.
04-25 08:09:38.326 I/ActivityManager(2087): Displayed com.SecUpwN.AIMSICD/.AIMSICD: +1s686ms
04-25 08:09:38.326 I/Timeline(2087): Timeline: Activity_windows_visible id: ActivityRecord{41e527c0 u0 com.SecUpwN.AIMSICD/.AIMSICD t4} time:41778413
04-25 08:09:38.446 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:38.566 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:51.739 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:52.060 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:58.316 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:09:58.436 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:58.566 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:58.936 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:09:59.096 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:09:59.287 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:01.631 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:01.731 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:11.870 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:10:11.991 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:12.101 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:12.731 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:12.811 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:18.577 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:10:18.777 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:18.877 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:19.007 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:10:19.148 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:19.228 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:19.478 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:10:19.618 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:19.708 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:22.020 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:10:22.200 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:22.351 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:30.579 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:30.689 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:32.310 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:32.420 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
04-25 08:10:32.811 V/AIMSICD (15378): DbAdapter: Cell info updated in local db: 6259818
(+40 more times the same update)
04-25 08:10:59.016 E/AndroidRuntime(15378): Process: com.SecUpwN.AIMSICD, PID: 15378
04-25 08:10:59.016 E/AndroidRuntime(15378): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.locationExists(AIMSICDDbAdapter.java:602)
04-25 08:10:59.016 E/AndroidRuntime(15378): 	at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertLocation(AIMSICDDbAdapter.java:418)
04-25 08:10:59.016 E/AndroidRuntime(15378): 	at com.SecUpwN.AIMSICD.service.CellTracker.onLocationChanged(CellTracker.java:987)
04-25 08:10:59.016 E/AndroidRuntime(15378): 	at com.SecUpwN.AIMSICD.service.AimsicdService$5.onLocationChanged(AimsicdService.java:274)
04-25 08:10:59.016 E/AndroidRuntime(15378): 	at com.SecUpwN.AIMSICD.service.LocationTracker$MyLocationListener.onLocationChanged(LocationTracker.java:152)
04-25 08:11:10.599 I/ActivityManager(2087): Process com.SecUpwN.AIMSICD (pid 15378) has died.
04-25 08:11:10.599 I/WindowState(2087): WIN DEATH: Window{4207ecb8 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
04-25 08:11:10.599 W/ActivityManager(2087): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
04-25 08:11:11.630 I/ActivityManager(2087): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=15580 uid=10158 gids={50158, 3003, 1028, 1023, 1007, 1015, 3006}
04-25 08:11:11.750 D/ActivityThread(15580): handleBindApplication:com.SecUpwN.AIMSICD
04-25 08:11:12.001 I/AIMSICD_Service(15580): Service launched successfully.
04-25 08:11:12.011 D/AIMSICD (15580): CellTracker: NC list not supported by AOS on this device. Nothing to do. CID: 6259818
04-25 08:11:12.011 D/AIMSICD (15580): CellTracker: Setting nc_list_present to: false
04-25 08:11:12.181 V/AIMSICD (15580): LAC checked - no change on CID:6259818 LAC(API): 22095 LAC(DBi): 22095
04-25 08:11:12.251 V/NlpLocationProvider(2409): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10158 com.SecUpwN.AIMSICD}
04-25 08:11:12.281 I/AIMSICD_SignalStrengthTracker(15580): Ignored signal strength sample for CID: 6259818 as the device is currently moving around, will not accept anything for another 29980 ms.
04-25 08:11:12.381 V/AIMSICD (15580): DbAdapter: Cell info updated in local db: 6259818
04-25 08:11:12.491 V/AIMSICD (15580): DbAdapter: Cell info updated in local db: 6259818
```

Then I press 'OK' on the popup application crashes 2-3 more times just after pressing OK, then starts without problems.

**Comment by E3V3A** [comment]
I've seen this too, and I've been suspecting the process governor. When a process is using too much CPU, it gets killed after a while. I have no idea how to check this. You may also consider looking at the other logcat buffers as well. `-b main -b events -b system -b radio`...

**Comment by agilob** [comment]
I'm not sure if that explains those crashes. Application dies immediately after turning on GPS.

1. No location service available
2. Turn on AIMSICD
3. Turn on GPS
4. Application crashes immediately
5. AIMSICD restarts itself
6. Crashes in less than two seconds
7. ...

**Comment by agilob** [comment]
Apparently it happens only when application is running as system-app

**Comment by SecUpwN** [comment]
>Apparently it happens only when application is running as system-app
You mean with root rights  a doing so and nothing crashes at all..

**Comment by agilob** [comment]
As system app, to do so copy AIMSICD.apk to /system/priv-app/ (android 4+?) and reboot your device, application will run as system app, not only with root privileges. You won't be able to reinstall/uninstall the application now. Do you have that com.google.calculator that requires internet connection and you can't uninstall it? remove it from /system/priv-apk and you will be able ;)

http://stackoverflow.com/questions/19868138/aosp-privileged-vs-system-app
http://www.addictivetips.com/mobile/how-to-install-any-app-as-system-app-on-android/

[mission impossible android](https://blog.torproject.org/blog/mission-impossible-hardening-android-security-and-privacy) requires a lot of digging in system apps, I got interested about it and made 'privacy phone' from my phone, I removed all calculators, notes, text messaging apps that required network connection or full device permissions. Instead I installed FDroid, AIMSICD, SMSSecure as system apps ;) FDroid as system-app is not stable too.

**Comment by SecUpwN** [comment]
>made 'privacy phone' from my phone

What you've installed seems great, but when uninstalling system apps you still have the deeply hidden spy- and bloatware on your system. I highly recommend to use a fresh custom ROM like my beloved [AOKP](http://aokp.co) as the base and then install the apps you've mentioned. Sounds better, huh?

Back to the crash in this Issue: Can you trace down what exactly causes this?

**Comment by agilob** [comment]
AOKP doesn't have ROM for my device, I use [carbonrom](https://carbonrom.org/screenshots/) ;)

> Can you trace down what exactly causes this?
I can try.

**Comment by SecUpwN** [comment]
@agilob, please test the current APK I have just sent to you and close this if fixed.

**Comment by E3V3A** [comment]
Hm, I never actually tried to install AIMSICD as a system app, since we loosely require root and included all related system permissions, thus it was not necessary. At least until now, if L requires it to be. @agilob Is there any particular reason you wanna make this a system app? (Problem with using this as system app is that it is not easily updated, which would be bad because of our current alpha status, with frequent and important updates.)

**Comment by SecUpwN** [comment]
@agilob would you please re-verify this Issue again? Please really *maintain* your Issues! ;-)

**Comment by agilob** [comment]
I'm unable to start application at all since 22.06. Crashes on start.

**Comment by SecUpwN** [comment]
>I'm unable to start application at all since 22.06. Crashes on start.

Did you also try a fresh install and removing any old data? Please add a fresh logcat for us.

**Comment by agilob** [comment]
I'm testing it. I'll be back here later

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)
