### ISSUE TITLE
More exceptions from database

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#483]
After update from master to development:

```
06-18 16:58:05.945  13424-13424/com.SecUpwN.AIMSICD W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4182bce0)
06-18 16:58:05.955  13424-13424/com.SecUpwN.AIMSICD E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.SecUpwN.AIMSICD, PID: 13424
    java.lang.RuntimeException: Unable to create service com.SecUpwN.AIMSICD.service.AimsicdService: android.database.sqlite.SQLiteException: table cells has no column named Lat (code 1): , while compiling: CREATE INDEX IF NOT EXISTS _idxspatial ON cells (Lat, Lng);
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2618)
            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.database.sqlite.SQLiteException: table cells has no column named Lat (code 1): , while compiling: CREATE INDEX IF NOT EXISTS _idxspatial ON cells (Lat, Lng);
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1672)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1603)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter$DbHelper.onOpen(AIMSICDDbAdapter.java:1431)
```
After a few restarts another exception caused by: `LACELLS_TABLE_CREATE` should be `CREATE TABLE IF NOT EXISTS ` - Table already exists.

**Comment by SecUpwN** [comment]
We need to implement #215 first.

**Comment by E3V3A** [comment]
I think this has been resolved by https://github.com/DJaeger/Android-IMSI-Catcher-Detector/commit/aefcce93363e71ebc28a554230bfc12399ff1e84
