### ISSUE TITLE
NaN exception when inserting into the database before GPS lock-on

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#487]
I still wasn't connected to GPS, device was getting fix. I had 'location' from Mozilla WiFi locator.

```
06-18 17:12:02.621  21260-21260/com.SecUpwN.AIMSICD V/AIMSICD﹕ DbAdapter: New Cell found, insert into local db:: 11363
06-18 17:12:02.711  21260-21260/com.SecUpwN.AIMSICD V/AIMSICD﹕ DbAdapter: Cell info updated in local db: 11363
06-18 17:12:06.635  21260-21260/com.SecUpwN.AIMSICD E/SQLiteLog﹕ (1) no such column: NaN
06-18 17:12:06.645  21260-21260/com.SecUpwN.AIMSICD D/AndroidRuntime﹕ Shutting down VM
06-18 17:12:06.645  21260-21260/com.SecUpwN.AIMSICD W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4182bce0)
06-18 17:12:06.655  21260-21260/com.SecUpwN.AIMSICD E/AndroidRuntime﹕ FATAL EXCEPTION: main

    Process: com.SecUpwN.AIMSICD, PID: 21260
    android.database.sqlite.SQLiteException: no such column: NaN (code 1): , while compiling: SELECT * FROM locationinfo WHERE CellID = 11363 AND Lat = NaN AND Lng = NaN AND Signal = 9
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
            at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.locationExists(AIMSICDDbAdapter.java:627)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertLocation(AIMSICDDbAdapter.java:433)
            at com.SecUpwN.AIMSICD.service.CellTracker.onLocationChanged(CellTracker.java:972)
            at com.SecUpwN.AIMSICD.service.AimsicdService$5.onLocationChanged(AimsicdService.java:263)
            at com.SecUpwN.AIMSICD.service.LocationTracker$MyLocationListener.onLocationChanged(LocationTracker.java:155)
            at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:279)
            at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:208)
            at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:224)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

I'm starting to think it wasn't even tested :<

**Comment by SecUpwN** [comment]
We need to implement #215 first.

**Comment by E3V3A** [comment]
Yep, I think the input vars for the `Lat = ? AND Lng = ?` substitution is not checked for NaNs. 

I also think this with #309 would decrease the FC rate and initial start up issues that seem random, but usually GPS related.

**Comment by E3V3A** [comment]
@agilob Is this issue still valid?

**Comment by E3V3A** [comment]
Closing...
