### ISSUE TITLE
I click the Antenna Map Viewer at the slide bar and crashed.

### ISSUE THREAD

**Issue by SpringXu-Git** [SecUpwN/Android-IMSI-Catcher-Detector#632]
Log:
```
FATAL EXCEPTION: AsyncTask #1
com.SecUpwN.AIMSICD E/AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 14623
com.SecUpwN.AIMSICD E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
com.SecUpwN.AIMSICD E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:304)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)
com.SecUpwN.AIMSICD E/AndroidRuntime:  Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=3
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.String.startEndAndLength(String.java:588)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.String.substring(String.java:1475)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid.loadOcidMarkersByNetwork(MapViewerOsmDroid.java:574)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid.access$500(MapViewerOsmDroid.java:91)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid$4.doInBackground(MapViewerOsmDroid.java:400)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid$4.doInBackground(MapViewerOsmDroid.java:392)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841) 
```

**Comment by smarek** [comment]
Handled by PR #639
