### ISSUE TITLE
Crash with new Pop Up system in SmsDetector.

### ISSUE THREAD

**Issue by banjaxbanjo** [SecUpwN/Android-IMSI-Catcher-Detector#677]
@larsgrefer Hey mate there appears to be a crash when an alert is detected in SmsDetector.

    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:200)
            at android.os.Handler.<init>(Handler.java:114)
            at android.app.Dialog.<init>(Dialog.java:112)
            at android.app.Dialog.<init>(Dialog.java:152)
            at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:42)
            at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:92)
            at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:882)
            at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:901)
            at com.SecUpwN.AIMSICD.smsdetection.SmsDetector.startPopUpInfo(SmsDetector.java:105)
            at com.SecUpwN.AIMSICD.smsdetection.SmsDetector.parseWapPushSms(SmsDetector.java:336)
            at com.SecUpwN.AIMSICD.smsdetection.SmsDetector.run(SmsDetector.java:223)

I'd this problem too when trying to create a dialog from a Thread class and I think that's why I did the popup on a new activity.

needs something like runOnUiThread to avoid crash.

```Java
        new AlertDialog.Builder(mContext)
                .setTitle(smsType.getTitle())
                .setMessage(smsType.getMessage())
                .setIcon(R.drawable.sense_danger)
                .show();
```

**Comment by larsgrefer** [comment]
Thats a bit difficult, even if the DIalog is created (and shown) on the UI-Thread the mContext object is a Service and has now window attatched to show the dialog in

**Comment by banjaxbanjo** [comment]
Ya pain in ass you can leave this to me if you like will try sort it when I get time so you are not swamped with pr's.

maybe an intent would solve this. What solution would you use lars

**Comment by larsgrefer** [comment]
In my opion the notification is enough and we don't need an additional dialog.
